name: Build Debian package
description: Build Debian package from source for selected target release
branding:
  color: red
  icon: package
inputs:
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: "./"
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: "./"
  target_architectures:
    description: Comma-separated options list of target architectures to build for
    required: false
    default: ""
  dpkg_buildpackage_opts:
    description: Comma-separated options list provided to 'dpkg-buildpackage' as command line parameters (note that '-a' is automatically provided for target architectures specified by target_architectures)
    required: false
    default: "--no-sign, -d"
  lintian_opts:
    description: Comma-separated options list provided to 'lintian' as command line parameters
    required: false
    default: ""
  get_dev_packages_from_backports:
    description: Only set to 1 if you know what you are doing. All other values are considered as 0
    required: false
    default: "0"

runs:
  using: node12
  main: main.js
