name: Build Debian package
description: Build Debian package from source for selected target release
branding:
  color: red
  icon: package
inputs:
  cpu_architecture:
    description: Target CPU architecture (amd64, arm64, arm, ...)
    required: false
    default: amd64
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: ./
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: ./
  os_distribution:
    description: OS distribution name, value from `debian/changelog` is used if not defined
    required: false
  target_release:
    description: additional releases (buster-security, buster-backports, etc), space-separated
    required: false
runs:
  using: node12
  main: main.js
  post: post.js
