name: Build Debian package
description: Build Debian package from source for selected target release
branding:
  color: red
  icon: package
inputs:
  cpu_architecture:
    description: Target CPU architecture
    required: false
    default: amd64
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: ./
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: ./
runs:
  using: node12
  main: main.js
  post: post.js
